/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CoreSidebar {
        "collapse": () => Promise<void>;
        "expand": () => Promise<void>;
        /**
          * Prop to define if sidebar is expanded or not
         */
        "expanded": boolean;
        "toggle": () => Promise<void>;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCoreSidebarElement extends Components.CoreSidebar, HTMLStencilElement {
    }
    var HTMLCoreSidebarElement: {
        prototype: HTMLCoreSidebarElement;
        new (): HTMLCoreSidebarElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "core-sidebar": HTMLCoreSidebarElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CoreSidebar {
        /**
          * Prop to define if sidebar is expanded or not
         */
        "expanded"?: boolean;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "core-sidebar": CoreSidebar;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "core-sidebar": LocalJSX.CoreSidebar & JSXBase.HTMLAttributes<HTMLCoreSidebarElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
